# Generated by Django 6.0.6 on 2026-09-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DownloadTask",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("owner", models.JSONField(default=list)),
                ("created_by", models.CharField(max_length=50)),
                ("modified_by", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="QUEUED", max_length=20)),
                ("total_files", models.IntegerField(default=0)),
                ("downloaded_files", models.IntegerField(default=0)),
                ("failed_files", models.IntegerField(default=0)),
                ("headers", models.JSONField(default=dict)),
                ("throttle", models.IntegerField(default=0)),
                ("task_dir", models.CharField(max_length=500)),
            ],
        ),
    ]
